const fs=require('node:fs/promises');const {readFileSync}=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');const assert=require('node:assert/strict');const {test,after}=require('node:test');const {randomUUID}=require('node:crypto');
function load(name,deps={}){const f=path.resolve(name);const m=new Module(f);m.filename=f;m.paths=module.paths;const original=m.require.bind(m);m.require=r=>r in deps?deps[r]:original(r);m._compile(ts.transpileModule(readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);return m.exports;}
const policy=load('lib/delegated-policy.ts');let failMail=false;let deliveries=0;
const intake=load('lib/project-intake.ts',{'./delegated-policy':policy,nodemailer:{createTransport:()=>({sendMail:async()=>{deliveries++;if(failMail)throw new Error('simulated mail failure');}})}});
const route=load('app/api/delegated-project/route.ts',{'@/lib/project-intake':intake});
const originalEnv={...process.env};let dir;
const data=()=>({requestId:randomUUID(),name:'测试伙伴',phone:'13800000000',company:'',project:'测试项目',city:'广州',propertyType:policy.PROPERTY_TYPES[0],owner:'测试主体',relationship:'已联系项目负责人，等待会面',need:'评估运营方案',contactStage:policy.CONTACT_STAGES[0],role:'refer',strategic:false,consent:true,source:'测试',assessment:{...policy.EMPTY_ASSESSMENT}});
const req=(v,headers={})=>new Request('http://localhost:3101/api/delegated-project',{method:'POST',headers:{origin:'http://localhost:3101','content-type':'application/json',...headers},body:JSON.stringify(v)});
after(async()=>{if(dir)await fs.rm(dir,{recursive:true,force:true});for(const k of Object.keys(process.env))if(!(k in originalEnv))delete process.env[k];Object.assign(process.env,originalEnv);});
test('disabled intake refuses data instead of returning fake success',async()=>{delete process.env.PROJECT_INTAKE_ENABLED;assert.equal((await route.POST(req(data()))).status,503);});
test('private storage config blocks public/build/Git paths',async()=>{for(const folder of ['public/intake','.next/intake','.git/intake']){process.env.PROJECT_INTAKE_DIR=path.resolve(folder);assert.throws(()=>intake.intakeDirectory());}dir=await fs.mkdtemp(path.resolve('tmp/intake-test-'));process.env.PROJECT_INTAKE_DIR=dir;process.env.PROJECT_INTAKE_ENABLED='true';process.env.SMTP_USER='test';process.env.SMTP_PASS='test';process.env.MAIL_TO='test@example.invalid';assert.equal(intake.intakeEnabled(),true);});
test('server validates identity, limits, consent, enums and strips untrusted grade',()=>{const v=data();for(const patch of [{consent:false},{phone:'bad'},{role:'__proto__'},{propertyType:'unknown'},{name:'x'.repeat(81)},{requestId:'../x'},{assessment:{...v.assessment,area:-1}},{website:'bot'}])assert.throws(()=>intake.parseIntake({...v,...patch}));assert.equal(intake.parseIntake({...v,grade:'A',protectionStart:'today'}).grade,undefined);});
test('concurrent duplicate retries save exactly one complete private record',async()=>{const v=intake.parseIntake(data());const records=await Promise.all(Array.from({length:8},()=>intake.saveIntake(v)));assert.equal(new Set(records.map(r=>r.record.receipt)).size,1);assert.equal(records.filter(r=>!r.duplicate).length,1);const file=path.join(dir,intake.recordKey(v.requestId)+'.json');const saved=JSON.parse(await fs.readFile(file));assert.equal(saved.assessment.grade,null);assert.equal(saved.status,'submitted');assert.equal(saved.policyVersion,'2.0');assert.equal(saved.protectionStart,undefined);assert.equal((await fs.stat(file)).mode&0o777,0o600);assert.equal((await fs.readdir(dir)).filter(f=>f.endsWith('.tmp')).length,0);await assert.rejects(()=>intake.saveIntake({...v,project:'另一项目'}),/REQUEST_ID_CONFLICT/);});
test('CSRF, media type and oversized bodies are rejected',async()=>{assert.equal((await route.POST(req(data(),{origin:'https://other.example'}))).status,403);assert.equal((await route.POST(req(data(),{'content-type':'text/plain'}))).status,415);assert.equal((await route.POST(req({large:'x'.repeat(33000)}))).status,413);});
test('server recomputes grade and returns no submitted PII',async()=>{const v={...data(),phone:'13800000001',assessment:{location:5,transport:4,amenities:3,strategy:3,area:100000,revenue:10000000,occupancy:90,guarantee:5,staff:50}};const response=await route.POST(req(v));assert.equal(response.status,202);assert.equal(response.headers.get('cache-control'),'no-store');const body=await response.json();assert.equal(body.status,'submitted');assert.equal(body.notification,'sent');assert.equal(body.intake,undefined);const saved=JSON.parse(await fs.readFile(path.join(dir,intake.recordKey(v.requestId)+'.json')));assert.equal(saved.assessment.total,100);assert.equal(saved.assessment.grade,'A');const again=await(await route.POST(req(v))).json();assert.equal(again.receipt,body.receipt);});
test('notification failure preserves record and allows later retry',async()=>{failMail=true;const v={...data(),phone:'13800000002'};const body=await(await route.POST(req(v))).json();assert.equal(body.ok,true);assert.equal(body.notification,'pending');assert.ok(await fs.readFile(path.join(dir,intake.recordKey(v.requestId)+'.json')));failMail=false;const again=await(await route.POST(req(v))).json();assert.equal(again.receipt,body.receipt);assert.equal(again.notification,'sent');});
test('persistence failure does not acknowledge receipt',async()=>{const bad=path.join(dir,'not-a-directory');await fs.writeFile(bad,'test');process.env.PROJECT_INTAKE_DIR=bad;const r=await route.POST(req({...data(),phone:'13800000003'}));assert.equal(r.status,503);assert.equal((await r.json()).ok,false);process.env.PROJECT_INTAKE_DIR=dir;});
test('per-contact throttle has an explicit retry response',async()=>{for(let i=0;i<5;i++)assert.equal((await route.POST(req({...data(),phone:'13800000004'}))).status,202);assert.equal((await route.POST(req({...data(),phone:'13800000004'}))).status,429);});
